### ISSUE TITLE
What is the pytorch_pretrained_bert package?

### ISSUE THREAD

**Issue by xbdxwyh** [Suo-Wei/SRCF#1]
Great work, and thanks for your sharing!
When I reproduce this work, the following error occurs.
```
Traceback (most recent call last):
  File "E:\Share\jupyterDir\SRCF-main\SRCF-main\src\test.py", line 8, in <module>
    from data.dataloader import get_dataloader
  File "E:\Share\jupyterDir\SRCF-main\SRCF-main\src\data\dataloader.py", line 9, in <module>
    from data.dataset import CUHKPEDEDataset, CUHKPEDE_img_dateset, CUHKPEDE_txt_dateset
  File "E:\Share\jupyterDir\SRCF-main\SRCF-main\src\data\dataset.py", line 17, in <module>
    from pytorch_pretrained_bert.tokenization import BertTokenizer
ModuleNotFoundError: No module named 'pytorch_pretrained_bert'
```
And I cannot find this package in all files.

**Comment by Suo-Wei** [comment]
This is a python package, it can be installed by pip install pytorch-pretrained-bert
